

development:
 adapter: sqlserver
 mode: dblib
 host: yourservername.database.windows.net
 database: yourdatabasename
 username: yourusername@yourservername
 password: password
 timeout: 5000
 azure: true
